"""
Social commands
"""

# Directed at user, with prepositions (first is default)
social('agree', 'with')
social('apologise', 'to')
social('argue', 'with')
social('bark', 'at')
social('beam', 'at')
social('beckon', 'to')
social('beep', 'at')
social('bing', 'at')
social('bingle', 'at')
social('bleep', 'at')
social('blink', 'at')
social('blush', 'at')
social('bow', 'to')
social('bouce', 'around')
social('cackle', 'at', 'to')
social('caper', 'around')
social('chuckle', 'at', 'to')
social('chortle', 'at')
social('complain', 'to')
social('confess', 'to')
social('cough', 'at', 'on')
social('cower', 'behind')           
social('crash', 'into')         
social('cringe', 'at')          
social('croak', 'at')
social('croon', 'at')
social('cuddle', 'up with')
social('curl', 'up with')
social('curse', 'at')
social('curtsey', 'to')
social('dance', 'with')         
social('disagree', 'with')          
social('discriminate', 'against')           
social('dribble', 'on')
social('drool', 'on')
social('eek', 'at')
social('eep', 'at')
social('fart', 'on')
social('fib', 'to')
social('fiddle', 'with')
social('flirt', 'with')
social('flutter', 'around')
social('frolic', 'around')
social('frown', 'at')
social('gape', 'at')
social('gasp', 'at')
social('gawk', 'at')
social('gaze', 'at')
social('gesticulate', 'to')
social('gesture', 'to')
social('giggle', 'at')
social('glare', 'at')
social('gloat', 'at', 'to')
social('glower', 'at')
social('grin', 'at')
social('grimace', 'at')
social('grind', 'with', 'on', 'against')
social('groan', 'at')
social('grovel', 'before')          
social('growl', 'at')           
social('grumble', 'at')         
social('grunt', 'at')
social('guffaw', 'at')
social('gulp', 'at')
social('hiccup', 'at')  ;       
social('hiss', 'at')
social('hoot', 'at')
social('hop', 'around')
social('howl', 'at')
social('hrmph', 'at')
social('hmm', 'at')
social('hrm', 'at')
social('hum', 'to')         
social('jump', 'on')
social('laugh', 'at', 'with')
social('lecture', 'to')
social('leer', 'at')
social('listen', 'to')
social('loom', 'over')
social('meep', 'at')
social('meow', 'at', 'to')
social('mime', 'to')
social('moan', 'at', 'to')
social('moo', 'at')
social('moose', 'at')
social('mope', 'at')
social('mumble', 'at', 'to')
social('mutter', 'at', 'to')
social('neigh', 'at')
social('nestle', 'up to')
social('nod', 'at', 'to')          
social('ook', 'at')         
social('ping', 'at')
social('plead', 'to')
social('point', 'at', 'to')
social('pose', 'for')
social('pounce', 'on')
social('pout', 'at')
social('prance', 'around')
social('propose', 'to')
social('puke', 'at', 'on', 'all over')
social('purr', 'at')
social('quack', 'at')
social('rant', 'at', 'to')
social('roar', 'at')
social('scamper', 'around')         
social('scoff', 'at')
social('scowl', 'at')
social('scream', 'at')
social('screech', 'at')
social('shrug', 'at')           
social('shiver', 'at')          
social('shriek', 'at')
social('shudder', 'at')         
social('sigh', 'at')
social('sing', 'to')
social('sit', 'on')
social('slobber', 'on')
social('smile', 'at')
social('smirk', 'at')
social('snap', 'at')
social('snarl', 'at')
social('sneer', 'at')
social('sneeze', 'at')
social('snicker', 'at')
social('sniff', 'at')
social('sniffle', 'at')
social('snigger', 'at', 'to')
social('snore', 'at')
social('snort', 'at')
social('snortle', 'at')
social('snore', 'at')
social('sob', 'at')
social('somersault', 'at')
social('sparkle', 'at')
social('spit', 'at', 'on')
social('spy', 'on')
social('squeak', 'at')
social('squeal', 'at')
social('squint', 'at')
social('stare', 'at')
social('sulk', 'at', 'to')
social('swagger', 'at')
social('swear', 'at', 'to')
social('sympathise', 'with')
social('tango', 'with')         
social('tattle', 'on')          
social('think', 'about')
social('tremble', 'at')         
social('tut', 'at')         
social('twinkle', 'at')         
social('twirl', 'at', 'around')
social('twitch', 'at')          
social('vomit', 'at', 'on')
social('wail', 'at')
social('wait', 'for')
social('waltz', 'with')
social('wave', 'at', 'to')
social('weep', 'at')
social('whimper', 'at', 'to')
social('whine', 'at', 'to')
social('whinge', 'at')
social('whinny', 'at')
social('whistle', 'to')
social('wibble', 'at')
social('wince', 'at')
social('wiggle', 'at')
social('wink', 'at')
social('wobble', 'at')
social('worry', 'about', 'at')
social('yawn', 'at')
social('yodel', 'at')
social('yelp', 'at')

# Directed at user, without prepositions
social('accuse')
social('annoy')
social('bite')
social('blame')
social('bribe')
social('caress')
social('chase')
social('chastise')
social('comfort')
social('compliment')
social('condemn')
social('congratulate')
social('defenestrate')
social('distract')
social('educate')
social('elbow')
social('encourage')
social('envy')
social('embarrass')
social('embrace')
social('flash')         
social('flatter')           
social('fondle')
social('forgive')           
social('glomp')
social('grab')          
social('greet')         
social('grope')         
social('hassle')    
social('headbutt')
social('highfive')
social('hit')
social('hug')
social('hush')
social('kick')
social('kiss')
social('lick')
social('love')
social('lynch')
social('massage')
social('mesmerise')
social('moon')
social('mourn')
social('nag')
social('nudge')         
social('obey')
social('ogle')
social('pat')
social('patronise')
social('pinch')
social('pity')
social('pamper')
social('pester')
social('pet')
social('poke')
social('prod')
social('praise')
social('preen')
social('promise')
social('punch')
social('punish')
social('push')
social('ram')
social('ravish')
social('rub')
social('remind')
social('salute')
social('satisfy')
social('scare')
social('scold')
social('scratch')
social('sedate')
social('seduce')
social('sentence')
social('serenade')
social('shake')
social('shoo')
social('shove')
social('shun')
social('shush')
social('slap')
social('smack')
social('smooch')
social('snog')
social('soothe')
social('spam')
social('spank')
social('squeeze')
social('stalk')
social('strangle')
social('stroke')
social('sue')
social('surprise')
social('tackle')
social('taunt')
social('tease')
social('tempt')
social('thank')
social('threaten')
social('tickle')
social('toast')
social('tongue')
social('touch')
social('trust')
social('warn')
social('welcome')

# Adjectives
social('applaud')           
social('boo')
social('bleat')
social('bleed')
social('breakdance')
social('breathe')
social('burp')
social('cheer')     
social('chew')
social('clap')  
social('code')          
social('collapse')  
social('cry')   
social('daydream')
social('declare')       
social('duck')
social('explode')
social('faint')
social('fall')
social('feel')
social('fidget')
social('glow')
social('gurgle')
social('hate')  
social('idle')
social('melt')
social('nap')
social('panic')
social('pant')
social('ponder')
social('protest')
social('prepare')
social('quote')
social('relax')
social('sleep')
social('spin')
social('squirm')
social('stagger')
social('stumble')
social('suck')
social('sweat')
social('volunteer')
social('win')           
social('wobble')
social('wonder')
