name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: py-${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.11"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Set Python path
        run: |
            echo "PYTHONPATH=." >> $GITHUB_ENV
      - name: Test
        run: |
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.python }}
